name: keithmaguire.net
markdown: redcarpet
pygments: true
prose:
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"

